import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
     <Head>        
        <meta name="description" content="Generated by create next app" />        
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="manifest.json" />
        <link rel="apple-touch-icon" href="img/nft-logo.png"></link>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
